...@../aws-nodes
...@../azure-nodes
...@../vmware-nodes


AZ-1{
    VPC.class:Virtual-private-cloud-VPC
    VPC{
        label:VPC-1478
    subnet{
    Server1.class:vm

    Server2.class:application  

    Server3.class:Arch_Amazon-RDS 
    }
}
}

AZ-2{
    VPC.class:Virtual-private-cloud-VPC
    VPC{
        label:VPC-1478
    subnet{
        Server1
    
        Server2
    
        Server3.class:Arch_Amazon-RDS
    }
    }
}

