classes:{
    alert {
        icon:../../assets/general/alert.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    all-products-dark {
        icon:../../assets/general/all-products-dark.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    all-products-light {
        icon:../../assets/general/all-products-light.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    application {
        icon:../../assets/general/application.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    authenticated-user {
        icon:../../assets/general/authenticated-user.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    camera {
        icon:../../assets/general/camera.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    chat {
        icon:../../assets/general/chat.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    client {
        icon:../../assets/general/client.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    code-file {
        icon:../../assets/general/code-file.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    cold-storage {
        icon:../../assets/general/cold-storage.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    credentials {
        icon:../../assets/general/credentials.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    data-center {
        icon:../../assets/general/data-center.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    data-stream {
        icon:../../assets/general/data-stream.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    database {
        icon:../../assets/general/database.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    disk {
        icon:../../assets/general/disk.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    document {
        icon:../../assets/general/document.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    documents {
        icon:../../assets/general/documents.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    email {
        icon:../../assets/general/email.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    firewall {
        icon:../../assets/general/firewall.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    folder {
        icon:../../assets/general/folder.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    folders {
        icon:../../assets/general/folders.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    forums {
        icon:../../assets/general/forums.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    general {
        icon:../../assets/general/general.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    git-repo {
        icon:../../assets/general/git-repo.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    globe {
        icon:../../assets/general/globe.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    internet-wireless {
        icon:../../assets/general/internet-wireless.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    internet {
        icon:../../assets/general/internet.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    JSON {
        icon:../../assets/general/JSON.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    logs {
        icon:../../assets/general/logs.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    management-console {
        icon:../../assets/general/management-console.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    marketplace-dark {
        icon:../../assets/general/marketplace-dark.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    marketplace-light {
        icon:../../assets/general/marketplace-light.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    sdk {
        icon:../../assets/general/sdk.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    secure {
        icon:../../assets/general/secure.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    server {
        icon:../../assets/general/server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    servers {
        icon:../../assets/general/servers.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    shield {
        icon:../../assets/general/shield.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    table {
        icon:../../assets/general/table.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    tape-storage {
        icon:../../assets/general/tape-storage.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    token {
        icon:../../assets/general/token.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    user {
        icon:../../assets/general/user.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    users {
        icon:../../assets/general/users.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    
}