classes {

    alert {
        icon:../../assets/vmware/alert.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    alignment {
        icon:../../assets/vmware/alignment.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    application {
        icon:../../assets/vmware/application.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    blueprint {
        icon:../../assets/vmware/blueprint.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    book {
        icon:../../assets/vmware/book.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    calendar {
        icon:../../assets/vmware/calendar.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    car {
        icon:../../assets/vmware/car.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    certificate-server {
        icon:../../assets/vmware/certificate-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    cloud-native-apps {
        icon:../../assets/vmware/cloud-native-apps.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    cog {
        icon:../../assets/vmware/cog.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    consumption-plane {
        icon:../../assets/vmware/consumption-plane.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    cpu {
        icon:../../assets/vmware/cpu.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    data-center {
        icon:../../assets/vmware/data-center.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    data-protection {
        icon:../../assets/vmware/data-protection.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    database-server {
        icon:../../assets/vmware/database-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    database {
        icon:../../assets/vmware/database.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    datastore {
        icon:../../assets/vmware/datastore.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    desktop {
        icon:../../assets/vmware/desktop.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    directory-server {
        icon:../../assets/vmware/directory-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    discovery {
        icon:../../assets/vmware/discovery.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    disk {
        icon:../../assets/vmware/disk.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    file {
        icon:../../assets/vmware/file.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    firewall {
        icon:../../assets/vmware/firewall.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    folder {
        icon:../../assets/vmware/folder.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    group {
        icon:../../assets/vmware/group.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    hard-disk {
        icon:../../assets/vmware/hard-disk.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    horizon {
        icon:../../assets/vmware/horizon.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    identity {
        icon:../../assets/vmware/identity.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    inftrastructure {
        icon:../../assets/vmware/inftrastructure.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    key {
        icon:../../assets/vmware/key.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    keyboard {
        icon:../../assets/vmware/keyboard.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    kubernetes {
        icon:../../assets/vmware/kubernetes.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    laptop {
        icon:../../assets/vmware/laptop.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    license {
        icon:../../assets/vmware/license.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    load-balancer {
        icon:../../assets/vmware/load-balancer.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    local-building {
        icon:../../assets/vmware/local-building.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    mail-server {
        icon:../../assets/vmware/mail-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    memory {
        icon:../../assets/vmware/memory.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    mobile-tower {
        icon:../../assets/vmware/mobile-tower.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    mobile {
        icon:../../assets/vmware/mobile.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    mouse {
        icon:../../assets/vmware/mouse.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    network-port {
        icon:../../assets/vmware/network-port.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    networking {
        icon:../../assets/vmware/networking.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx-controller {
        icon:../../assets/vmware/nsx-controller.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx-csm {
        icon:../../assets/vmware/nsx-csm.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx-dlr-control {
        icon:../../assets/vmware/nsx-dlr-control.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx-gateway {
        icon:../../assets/vmware/nsx-gateway.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx-manager {
        icon:../../assets/vmware/nsx-manager.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    nsx {
        icon:../../assets/vmware/nsx.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    physical-nic {
        icon:../../assets/vmware/physical-nic.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    pivotal {
        icon:../../assets/vmware/pivotal.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    pks {
        icon:../../assets/vmware/pks.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    psc {
        icon:../../assets/vmware/psc.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    public-cloud {
        icon:../../assets/vmware/public-cloud.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    rack-server {
        icon:../../assets/vmware/rack-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    rack-servers {
        icon:../../assets/vmware/rack-servers.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    reservation {
        icon:../../assets/vmware/reservation.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    router {
        icon:../../assets/vmware/router.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    scsi-controller {
        icon:../../assets/vmware/scsi-controller.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    security {
        icon:../../assets/vmware/security.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    self-service {
        icon:../../assets/vmware/self-service.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    server {
        icon:../../assets/vmware/server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    servers {
        icon:../../assets/vmware/servers.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    service-provider {
        icon:../../assets/vmware/service-provider.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    site-container {
        icon:../../assets/vmware/site-container.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    ssd {
        icon:../../assets/vmware/ssd.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    switch {
        icon:../../assets/vmware/switch.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    template {
        icon:../../assets/vmware/template.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    usb {
        icon:../../assets/vmware/usb.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    user {
        icon:../../assets/vmware/user.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vapp {
        icon:../../assets/vmware/vapp.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vcenter-server {
        icon:../../assets/vmware/vcenter-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    virtual-appliance {
        icon:../../assets/vmware/virtual-appliance.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    virtual-switch {
        icon:../../assets/vmware/virtual-switch.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vm-server {
        icon:../../assets/vmware/vm-server.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vm {
        icon:../../assets/vmware/vm.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmc-dellemc {
        icon:../../assets/vmware/vmc-dellemc.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmc {
        icon:../../assets/vmware/vmc.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-appdefense {
        icon:../../assets/vmware/vmware-appdefense.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cloud-assembly {
        icon:../../assets/vmware/vmware-cloud-assembly.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cloud-director {
        icon:../../assets/vmware/vmware-cloud-director.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cloud-foundation {
        icon:../../assets/vmware/vmware-cloud-foundation.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cloud-pks {
        icon:../../assets/vmware/vmware-cloud-pks.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cloud {
        icon:../../assets/vmware/vmware-cloud.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-code-stream {
        icon:../../assets/vmware/vmware-code-stream.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-cost-insight {
        icon:../../assets/vmware/vmware-cost-insight.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-hcx {
        icon:../../assets/vmware/vmware-hcx.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-nsx {
        icon:../../assets/vmware/vmware-nsx.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-nsxt {
        icon:../../assets/vmware/vmware-nsxt.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-nsxv {
        icon:../../assets/vmware/vmware-nsxv.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-pulse-iot {
        icon:../../assets/vmware/vmware-pulse-iot.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-secure-state {
        icon:../../assets/vmware/vmware-secure-state.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-service-catalog {
        icon:../../assets/vmware/vmware-service-catalog.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-site-recovery {
        icon:../../assets/vmware/vmware-site-recovery.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vcloud-extender {
        icon:../../assets/vmware/vmware-vcloud-extender.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-automation {
        icon:../../assets/vmware/vmware-vrealize-automation.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-business {
        icon:../../assets/vmware/vmware-vrealize-business.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-log-insight {
        icon:../../assets/vmware/vmware-vrealize-log-insight.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-network-insight {
        icon:../../assets/vmware/vmware-vrealize-network-insight.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-orchestraor {
        icon:../../assets/vmware/vmware-vrealize-orchestraor.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-orchestrator {
        icon:../../assets/vmware/vmware-vrealize-orchestrator.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vrealize-suite {
        icon:../../assets/vmware/vmware-vrealize-suite.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vsan {
        icon:../../assets/vmware/vmware-vsan.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vshield {
        icon:../../assets/vmware/vmware-vshield.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-vsphere-replication {
        icon:../../assets/vmware/vmware-vsphere-replication.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vmware-workspace-one {
        icon:../../assets/vmware/vmware-workspace-one.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vpn {
        icon:../../assets/vmware/vpn.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vrops {
        icon:../../assets/vmware/vrops.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    vxlan {
        icon:../../assets/vmware/vxlan.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    wavefront {
        icon:../../assets/vmware/wavefront.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    wi-fi {
        icon:../../assets/vmware/wi-fi.svg
        shape:image
        height:50
        style{
            font:mono
            font-size:14
        }
    }
    
    


}